{
 "title": "Typesense Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Requests Per Second", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "typesense_stats{key=\"total_requests_per_second\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Write Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "typesense_stats{key=\"write_requests_per_second\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Search Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "typesense_stats{key=\"search_requests_per_second\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Import Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "typesense_stats{key=\"import_requests_per_second\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Delete Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "typesense_stats{key=\"delete_requests_per_second\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Overloaded Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "typesense_stats{key=\"overloaded_requests_per_second\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Import Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "typesense_stats{key=\"import_latency_ms\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Search Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "typesense_stats{key=\"search_latency_ms\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "typesense_stats{key=\"write_latency_ms\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Delete Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "typesense_stats{key=\"delete_latency_ms\"}",
     "legendFormat": "{{key}}"
    }
   ]
  }
 ]
}